version: "3"
services:
  cpsdriver:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - "./data/downloads:/app/data/downloads"
    environment:
      - AIFI_CPSWEEK_COMP__TOKEN=${AIFI_CPSWEEK_COMP__TOKEN}
      - AIFI_CPSWEEK_COMP__DB_ADDRESS=${AIFI_CPSWEEK_COMP__DB_ADDRESS:-mongodb://cpsweek:localdb@mongodb:27017}
      - AIFI_CPSWEEK_COMP__API_ADDRESS=${AIFI_CPSWEEK_COMP__API_ADDRESS:-http://aifi.io/cpsweek/api/v1}
      - AIFI_CPSWEEK_COMP__COMMAND=${AIFI_CPSWEEK_COMP__COMMAND:-cps-test-01}
      - AIFI_CPSWEEK_COMP__SAMPLE=${AIFI_CPSWEEK_COMP__SAMPLE:-nodepth}
    ports:
      - "80:5000"
    links:
      - mongodb
    depends_on:
      - "mongodb"
  mongodb:
    image: mongo:4.2
    expose:
      - "27017"
    ports:
      - "27018:27017"
    volumes:
      - "./data/mongo:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: cpsweek
      MONGO_INITDB_ROOT_PASSWORD: localdb
